--DROP TABLE IF EXISTS QRTZ_FIRE_HISTORY;

CREATE TABLE QRTZ_FIRE_HISTORY(
  SCHED_NAME varchar(100) NOT NULL,
  TRIGGER_NAME varchar(110) NOT NULL,
  TRIGGER_GROUP varchar(110) NOT NULL,
  FIRED_TIME BIGINT(13) NOT NULL,
  SCHEDULED_TIME BIGINT(13) NOT NULL,
  STATE VARCHAR(16) NOT NULL,
  JOB_NAME  VARCHAR(200) NOT NULL,
  JOB_GROUP VARCHAR(200) NOT NULL,
  JOB_RUN_TIME BIGINT(13) NOT NULL,
  JOB_DATA BLOB NULL,
  
  PRIMARY KEY(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP, FIRED_TIME)
);